### ISSUE TITLE
发现系统的一个bug，和各位大大说说，看看你们是不是这样的

### ISSUE THREAD

**Issue by NetLogoclub** [cnodejs/nodeclub#848]
首先，我用github账号登录了一下cnodejs社区，然后我就点退出了，此时我想用另外一个邮箱来重新注册一个账号，我点击注册，这个时候社区就自己登陆了我github账号，竟然不给我注册界面。
希望各位大大测试的时候能够重现这个bug！

**Comment by liygheart** [comment]
这个不是bug
你登录github.com把自己的帐号退出，然后在cnodejs.org里重新登录在试试

**Comment by NetLogoclub** [comment]
这个肯定是bug啊，我github可以授权登录后，账号就是在cnodejs里创建了，但是cnodejs.org里我已经退出了啊，再点注册，此时怎么还去管github账号呢，应该看社区的账号了

**Comment by liygheart** [comment]
在config.deafult.js里有一个配置参数
```
// 是否允许直接注册（否则只能走 github 的方式）
allow_sign_up: true,
```
cnodejs.org估计指定了不允许本地注册，所以走的都是github方式

**Comment by NetLogoclub** [comment]
我去，好像这货真的只能走github，我把github号给退了，他真的只提示了github注册

**Comment by liygheart** [comment]
不是bug吧

**Comment by NetLogoclub** [comment]
我只能说这些大大们太能搞了

**Comment by alsotang** [comment]
现在官方这边关闭了常规的注册途径，只能通过 github oauth 注册，当你点注册的时候，它就会跳到 github
去要求你授权。当你github已经登录，并且已经授权的情况下，就自动跳回来了。

2016-05-25 9:53 GMT+08:00 NetLogoclub <notifications@github.com>:

**Comment by liygheart** [comment]
昨天调试github登录的时候，发现access_token居然每次都不一样，本来我数据库里是保存access_token来判断用户之前是否登录过的，现在只
能用github的用户id了

由于每次登录拿到的access_token都不一样，也就导致了登录一次，github上统计的用户数量就多一个，其实都是一个用户登录的，大大能讲解一下原理吗？

  

Sent from [Nylas N1](https://nylas.com/n1?ref=n1), the extensible, open source
mail client.  

On 5月 28 2016, at 5:47 下午, alsotang &lt;notifications@github.com&gt; wrote:  

> 现在官方这边关闭了常规的注册途径，只能通过 github oauth 注册，当你点注册的时候，它就会跳到 github  
去要求你授权。当你github已经登录，并且已经授权的情况下，就自动跳回来了。  
  
2016-05-25 9:53 GMT+08:00 NetLogoclub &lt;notifications@github.com&gt;:  
  
&gt; Closed #848 &lt;https://github.com/cnodejs/nodeclub/issues/848&gt;.  
&gt;  
&gt; —  
&gt; You are receiving this because you are subscribed to this thread.  
&gt; Reply to this email directly or view it on GitHub  
&gt; &lt;https://github.com/cnodejs/nodeclub/issues/848#event-671172384&gt;  
&gt;  

>

> —  
You are receiving this because you commented.  
Reply to this email directly, [view it on GitHub](https://github.com/cnodejs/n
odeclub/issues/848#issuecomment-222300036), or [mute the
thread](https://github.com/notifications/unsubscribe/AGmF8oGMtqz-Hbxqblew0-HPl
aG7kk_Kks5qGA83gaJpZM4ImEcO).![](https://github.com/notifications/beacon
/AGmF8pRvK3YjJzPAYcSr-pXWwg2UH1aUks5qGA83gaJpZM4ImEcO.gif)

**Comment by TakWolf** [comment]
@liygheart access_token 是有时效的，每一次登录肯定不一样。用id判断同一个用户是正确的思路

**Comment by liygheart** [comment]
@TakWolf github的id居然是double，不知道你发现了没？
